name: CI

on: # triggers
  pull_request:
    branches:
      - develop
  paths: # Participam do teste no Action
    - 'src/**'
    - 'tests/**'
    - 'package.json'
    - 'package-lock.json'
    - 'tsconfig.json'

  # paths-ignore: # Não participam do teste no Action
  #   - 'README.md'


env:
  PORT: ${{ vars.PORT }}
  API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Rodar os testes
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Rodar os build
        run: npm run build